# Generated by Django 5.0.6 on 2025-09-07 10:30

import django.contrib.postgres.fields
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactInquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullName', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=255)),
                ('phone', models.CharField(max_length=100)),
                ('company', models.CharField(blank=True, max_length=255)),
                ('subject', models.TextField()),
                ('status', models.CharField(choices=[('new', 'New'), ('handled', 'Handled')], default='new', max_length=50)),
                ('createdAt', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
            ],
            options={
                'ordering': ['-createdAt', '-id'],
            },
        ),
        migrations.CreateModel(
            name='PortfolioItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createdAt', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('title_en', models.CharField(max_length=255, null=True)),
                ('title_az', models.CharField(max_length=255, null=True)),
                ('title_ru', models.CharField(max_length=255, null=True)),
                ('description', models.TextField(blank=True)),
                ('description_en', models.TextField(blank=True, null=True)),
                ('description_az', models.TextField(blank=True, null=True)),
                ('description_ru', models.TextField(blank=True, null=True)),
                ('image', models.URLField(blank=True, max_length=500)),
                ('url', models.URLField(blank=True, max_length=500)),
                ('category', models.CharField(blank=True, max_length=100)),
                ('category_en', models.CharField(blank=True, max_length=100, null=True)),
                ('category_az', models.CharField(blank=True, max_length=100, null=True)),
                ('category_ru', models.CharField(blank=True, max_length=100, null=True)),
                ('technologies', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), blank=True, default=list, size=None)),
                ('client', models.CharField(blank=True, max_length=255)),
                ('client_en', models.CharField(blank=True, max_length=255, null=True)),
                ('client_az', models.CharField(blank=True, max_length=255, null=True)),
                ('client_ru', models.CharField(blank=True, max_length=255, null=True)),
                ('completionDate', models.DateField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-completionDate', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('createdAt', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('title_en', models.CharField(max_length=255, null=True)),
                ('title_az', models.CharField(max_length=255, null=True)),
                ('title_ru', models.CharField(max_length=255, null=True)),
                ('description', models.TextField(blank=True)),
                ('description_en', models.TextField(blank=True, null=True)),
                ('description_az', models.TextField(blank=True, null=True)),
                ('description_ru', models.TextField(blank=True, null=True)),
                ('details', models.TextField(blank=True)),
                ('details_en', models.TextField(blank=True, null=True)),
                ('details_az', models.TextField(blank=True, null=True)),
                ('details_ru', models.TextField(blank=True, null=True)),
                ('image', models.URLField(blank=True, max_length=500)),
                ('features', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), blank=True, default=list, size=None)),
                ('pricing', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createdAt', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('name_en', models.CharField(max_length=255, null=True)),
                ('name_az', models.CharField(max_length=255, null=True)),
                ('name_ru', models.CharField(max_length=255, null=True)),
                ('role', models.CharField(blank=True, max_length=255)),
                ('role_en', models.CharField(blank=True, max_length=255, null=True)),
                ('role_az', models.CharField(blank=True, max_length=255, null=True)),
                ('role_ru', models.CharField(blank=True, max_length=255, null=True)),
                ('image', models.URLField(blank=True, max_length=500)),
                ('bio', models.TextField(blank=True)),
                ('bio_en', models.TextField(blank=True, null=True)),
                ('bio_az', models.TextField(blank=True, null=True)),
                ('bio_ru', models.TextField(blank=True, null=True)),
                ('social', models.JSONField(blank=True, default=dict)),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createdAt', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('name_en', models.CharField(max_length=255, null=True)),
                ('name_az', models.CharField(max_length=255, null=True)),
                ('name_ru', models.CharField(max_length=255, null=True)),
                ('thoughts', models.TextField()),
                ('thoughts_en', models.TextField(null=True)),
                ('thoughts_az', models.TextField(null=True)),
                ('thoughts_ru', models.TextField(null=True)),
                ('role', models.CharField(blank=True, max_length=255)),
                ('role_en', models.CharField(blank=True, max_length=255, null=True)),
                ('role_az', models.CharField(blank=True, max_length=255, null=True)),
                ('role_ru', models.CharField(blank=True, max_length=255, null=True)),
                ('instagramUrl', models.URLField(blank=True, max_length=500)),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createdAt', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('title_en', models.CharField(max_length=255, null=True)),
                ('title_az', models.CharField(max_length=255, null=True)),
                ('title_ru', models.CharField(max_length=255, null=True)),
                ('excerpt', models.TextField(blank=True)),
                ('excerpt_en', models.TextField(blank=True, null=True)),
                ('excerpt_az', models.TextField(blank=True, null=True)),
                ('excerpt_ru', models.TextField(blank=True, null=True)),
                ('content', models.TextField()),
                ('content_en', models.TextField(null=True)),
                ('content_az', models.TextField(null=True)),
                ('content_ru', models.TextField(null=True)),
                ('category', models.CharField(blank=True, max_length=100)),
                ('category_en', models.CharField(blank=True, max_length=100, null=True)),
                ('category_az', models.CharField(blank=True, max_length=100, null=True)),
                ('category_ru', models.CharField(blank=True, max_length=100, null=True)),
                ('date', models.DateField()),
                ('readTime', models.CharField(blank=True, max_length=50)),
                ('readTime_en', models.CharField(blank=True, max_length=50, null=True)),
                ('readTime_az', models.CharField(blank=True, max_length=50, null=True)),
                ('readTime_ru', models.CharField(blank=True, max_length=50, null=True)),
                ('image', models.URLField(blank=True, max_length=500)),
                ('tags', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), blank=True, default=list, size=None)),
                ('status', models.CharField(choices=[('published', 'Published'), ('draft', 'Draft')], default='draft', max_length=20)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date', '-id'],
            },
        ),
    ]
