# Generated by Django 5.0.6 on 2025-10-11 22:00

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_category_remove_blogpost_category_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createdAt', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('question', models.CharField(max_length=500)),
                ('question_en', models.CharField(max_length=500, null=True)),
                ('question_az', models.CharField(max_length=500, null=True)),
                ('question_ru', models.CharField(max_length=500, null=True)),
                ('answer', models.TextField()),
                ('answer_en', models.TextField(null=True)),
                ('answer_az', models.TextField(null=True)),
                ('answer_ru', models.TextField(null=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'FAQ',
                'verbose_name_plural': 'FAQs',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.AddField(
            model_name='contactinquiry',
            name='updatedAt',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.CreateModel(
            name='HeaderNavLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createdAt', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=100)),
                ('title_en', models.CharField(max_length=100, null=True)),
                ('title_az', models.CharField(max_length=100, null=True)),
                ('title_ru', models.CharField(max_length=100, null=True)),
                ('url', models.CharField(help_text='Internal path or external URL', max_length=500)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_external', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('parent', models.ForeignKey(blank=True, help_text='Parent link for dropdown structure', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='core.headernavlink')),
            ],
            options={
                'verbose_name': 'Header Navigation Link',
                'verbose_name_plural': 'Header Navigation Links',
                'ordering': ['parent__id', 'order', 'id'],
            },
        ),
    ]
