# Generated by Django 5.0.6 on 2025-10-19 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_faq_contactinquiry_updatedat_headernavlink'),
    ]

    operations = [
        migrations.CreateModel(
            name='PortfolioCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('name_en', models.CharField(max_length=100, null=True, unique=True)),
                ('name_az', models.CharField(max_length=100, null=True, unique=True)),
                ('name_ru', models.CharField(max_length=100, null=True, unique=True)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Portfolio Category',
                'verbose_name_plural': 'Portfolio Categories',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.RemoveField(
            model_name='portfolioitem',
            name='category',
        ),
        migrations.RemoveField(
            model_name='portfolioitem',
            name='category_az',
        ),
        migrations.RemoveField(
            model_name='portfolioitem',
            name='category_en',
        ),
        migrations.RemoveField(
            model_name='portfolioitem',
            name='category_ru',
        ),
        migrations.AlterField(
            model_name='portfolioitem',
            name='technologies',
            field=models.ManyToManyField(blank=True, related_name='portfolio_technology_items', to='core.technology'),
        ),
        migrations.AddField(
            model_name='portfolioitem',
            name='categories',
            field=models.ManyToManyField(blank=True, related_name='portfolio_category_items', to='core.portfoliocategory'),
        ),
    ]
