# Generated by Django 5.0.6 on 2025-10-27 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_category_createdat_category_updatedat_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolioitem',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='service',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
