# Generated by Django 5.0.6 on 2025-10-27 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_service_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='order',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='contactinquiry',
            name='order',
            field=models.IntegerField(default=0),
        ),
    ]
